### ISSUE TITLE
Examples: OSX dos not support /dev/video* device

### ISSUE THREAD

**Issue by mmichal9** [wasmvision/wasmcv#1]
OSX does not support /dev/video devices rendering examples frozen without any error. 

Using gocv.VideoCaptureDevice(deviceID) instead seem to fix the issue

@deadprogram,  I have a PR ready to contribute the fix with small improvements in the example docs.
Please advise regarding contribution instructions :)

**Comment by mmichal9** [comment]
@deadprogram fix proposal: https://github.com/wasmvision/wasmcv/pull/2

**Comment by deadprogram** [comment]
Good point about the device ID!

**Comment by deadprogram** [comment]
Corrected by #2 thank you!
